config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#index'
  resources :articles, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :text, presence: true
end

app/models/ckeditor/asset.rb
# frozen_string_literal: true

class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
# frozen_string_literal: true

class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
# frozen_string_literal: true

class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private

  def configure_permitted_parameters
    # デフォルトのdevise以外のカラムを登録する際に記述
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :name])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == 'null'
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # before_action :move_to_index, except: [:index]
#
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else
      render :new
    end
 
  end

  private

  def article_params
    params.require(:article).permit(:title, :text).merge(user_id: current_user.id)
  end

  def move_to_index 
    unless user_signed_in?
      redirect_to action: :index      
    end
  end 

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/articles/index.html.erb
<div class="main-page">

  <%# ヘッダー %>
<%= render "shared/homeheader" %>

<div class="column">
<%# 左カラム %>
<div class="left-column">
  <div class="left-title-column">
    <h1 class="left-title">Ruby</h1>
    <%# 種類別に表示される機能 %>
    <%# プルダウンで選択できる機能 %>
  </div>
  <div class="choice">
    <%# スクロールで表示されるタグ %>
    <ul>
    <li>・Ruby</li>
    <li>・Rails</li>
    <li>・メソッド</li>
    <li>・etc...</li>
    </ul>
  </div>
  <div class="left-search">
    <form class="search-forms" action="#">
      <button class="search-buttons">
      検索
      </button>
      <input class='input-boxs' placeholder='言語別検索'>
      <%# placeholderにRuby,js,php内検索など指定した言語によって表示が変わるようにする。 %>
      <%# 言語別で検索できる機能 %>
  </div>
  <div class="result">
    <p class="result-search">検索結果</p>
    <%# left-searchで検索した結果が表示される %>
    <%# クリックしたらメインカラムにデータが表示される %>
    <div class="result-search-name">
    <% @articles.each do |article| %>
    <p>：<%= article.title %></p>
    <% end %>
    </div>
  </div>
</div>

<%# メインカラム %>
<div class="main-column">
<% @articles.each do |article| %>
  <div class="main-title">
    <h2 class="main-title-column">：<%= article.title %></h2>
    <%# resultでクリックしたタイトル %>
  </div>
  <div class="main-content">
      
      <span class="name">
        <%= raw article.text %>
      </span>
  </div>
  <% end %>
</div>

<%# 右カラム %>
<div class="right-column">
  <div class="table-content">
    <%# クリックしたら表示されている見出しにスクロールされる %>
    <ul>
      <li class="list-group-item">
        目次
        </li>
      <li class="list-item">・マイグレーション</li>
      <li class="list-item">・ロールバック</li>
      <li class="list-item">・リセット</li>
      <li class="list-item">・etc</li>
    </ul>
  </div>
  <div class="api-link">
  <a class="twitter-timeline" data-lang="ja" data-height="345" data-theme="dark" href="https://twitter.com/UN_NERV?ref_src=twsrc%5Etfw">Tweets by UN_NERV</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>
</div>
</div>
<%# フッター %>
<%= render "shared/homefooter" %>

app/views/articles/new.html.erb
  <%# ヘッダー %>
  <div class="header">
  <div class="header-title">
     <%= link_to 'ITDB 情報技術データベース', root_path, class: "title" %>
  </div>
  <div class="new-page">
    <%= link_to '新規投稿', new_article_path, class: "new-link-tag" %>
  </div>
  <div class="search">
    
  </div>
</div>

<div class="new-pages">
<h3>投稿する</h3>
    <%= form_with(model: @article, local: true) do |form| %>
      <%= form.text_field :title, placeholder: "Nickname" %>
      <%= form.text_area :text, placeholder: "text"%>
      <%= form.submit "SEND" %>
    <% end %>
  </div>

app/views/homes/index.html.erb
<div class="main">
<%= render "shared/homeheader" %>
    <div class="main-db">
      <div class="main-db-list">
        <p class="home-title">データベース一覧</p>
        <ul class="language-tag">
          <li><%= link_to 'Ruby', articles_path, class: "home-link-tag" %></li>
          <li><%= link_to 'javascript', "#", class: "home-link-tag" %></li>
          <li><%= link_to 'HTML&CSS', "#", class: "home-link-tag" %></li>
          <li><%= link_to 'WordPress', "#", class: "home-link-tag" %></li>
          <li><%= link_to 'HTTP', "#", class: "home-link-tag" %></li>
          <li><%= link_to 'PHP', "#", class: "home-link-tag" %></li>
          <li><%= link_to 'Python', "#", class: "home-link-tag" %></li>
          <li><%= link_to 'C言語', "#", class: "home-link-tag" %></li>
          <li><%= link_to 'JAVA', "#", class: "home-link-tag" %></li>
          <li><%= link_to 'Minecraftコード一覧', "#", class: "home-link-tag" %></li>
          <li><%= link_to 'フォネティックコード', "#", class: "home-link-tag" %></li>
          <li><%= link_to 'マーケティング', "#", class: "home-link-tag" %></li>
          <li><%= link_to 'その他知識', "#", class: "home-link-tag" %></li>
        </ul>
      </div>
    </div>

<%# ロード画面アニメーション %>
  <div id="js-loader" class="loader">
    <div class="loader-animation"></div>
  </div>

  <%= render "shared/homefooter" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ItdbVar20</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag Ckeditor.cdn_url %>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_homefooter.html.erb
<div class='footer'>
  <p>ITDB情報技術データベース &copy; 2021. All Rights Reserved.</p>
</div>

app/views/shared/_homeheader.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<div class="header">
  <div class="header-title">
     <%= link_to 'ITDB 情報技術データベース', root_path, class: "title" %>
  </div>
  <div class="new-page">
    <%= link_to '新規投稿', new_article_path, class: "myButton" %>
  </div>
  <div class="search">
    <form class="search-form" action="#">
      <button class="search-buttons">
      検索
      </button>
      <input class='input-box' placeholder='すべてを検索'>
  </div>
  <%# devise機能 %>
  <div class="sign_up">
    <p class="admin">管理者用</p>
    <ul class='lists-right'>
      <% if user_signed_in? %>
      <li class="devise"><%= link_to current_user.nickname, "#", class: "user-nickname" %> </li> 
      <li class="devise"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li> 
      <% else %>
      <li class="devise"><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li class="devise"><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</div>